# Generated by Django 4.2.7 on 2024-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slider_images/")),
                ("caption", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
