# Generated by Django 4.2.7 on 2024-04-13 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_secondsliderimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="001", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="group_deal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(default="007", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer_country",
            field=models.CharField(default="006", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="price_per_unit",
            field=models.CharField(default="003", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="product_number",
            field=models.CharField(default="your_default_value_here", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.CharField(default="002", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="trade_type",
            field=models.CharField(default="004", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_type",
            field=models.CharField(default="005", max_length=100),
        ),
    ]
