# Generated by Django 4.2.7 on 2024-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_product_brand_product_end_date_product_group_deal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
    ]
