# Generated by Django 4.2.7 on 2024-04-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("site", models.URLField()),
                ("gmail", models.EmailField(max_length=254)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
