# Generated by Django 4.2.7 on 2024-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_deal"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="status",
            field=models.CharField(default="Новый", max_length=50),
        ),
    ]
