# Generated by Django 4.2.7 on 2024-04-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_deal_status"),
    ]

    operations = [
        migrations.DeleteModel(name="MyModel",),
        migrations.AlterModelOptions(
            name="application",
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки"},
        ),
        migrations.AlterModelOptions(
            name="deal",
            options={"verbose_name": "Тендер", "verbose_name_plural": "Тендеры"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "Новости", "verbose_name_plural": "Новости"},
        ),
        migrations.AlterModelOptions(
            name="person", options={"verbose_name": "22", "verbose_name_plural": "22"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукт"},
        ),
        migrations.AlterModelOptions(
            name="productinfo",
            options={
                "verbose_name": "Продукт доп информация",
                "verbose_name_plural": "Продукт доп информация",
            },
        ),
        migrations.AlterModelOptions(
            name="secondsliderimage",
            options={
                "verbose_name": "Карусель моюильная версия",
                "verbose_name_plural": "Карусель моюильная версия",
            },
        ),
        migrations.AlterModelOptions(
            name="sliderimage",
            options={
                "verbose_name": "Карусель ПК версия",
                "verbose_name_plural": "Карусель ПК версия",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.URLField(
                default="https://www.gazeta.uz/oz/2024/04/13/yunusabad/"
            ),
        ),
    ]
