# Generated by Django 4.2.7 on 2024-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("image", models.ImageField(upload_to="images/")),
                ("text", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Галерея", "verbose_name_plural": "Галерея"},
        ),
    ]
