# Generated by Django 4.2.7 on 2024-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_logo_alter_image_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
