# Generated by Django 4.2.7 on 2024-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vazirlik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
            ],
        ),
    ]
