# Generated by Django 4.2.7 on 2024-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_vazirlik"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
