# Generated by Django 4.2.7 on 2024-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_employee_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
