# Generated by Django 5.0.4 on 2024-05-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='img',
            field=models.ImageField(default='tender/default.jpg', upload_to='tender/'),
        ),
    ]
