# Generated by Django 5.0.4 on 2024-05-27 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_deal_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
