# Generated by Django 5.0.4 on 2024-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_deal_expiration_date_deal_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
