# Generated by Django 5.0.6 on 2024-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_deal_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraktivXizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
