# Generated by Django 4.2.7 on 2024-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_delete_secondsliderimage_delete_sliderimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DavlatTashkilotlari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "DavlatTashkilotlari",
                "verbose_name_plural": "DavlatTashkilotlari",
            },
        ),
        migrations.CreateModel(
            name="ElektronHukumatDoirasidaAmalgaOshirilayotganLoyihalar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Elektron Hukumat Doirasida Amalga Oshirilayotgan Loyihalar",
                "verbose_name_plural": "Elektron Hukumat Doirasida Amalga Oshirilayotgan Loyihalar",
            },
        ),
        migrations.CreateModel(
            name="GenderTenglikAsosiyInsonHuquqlaridanBiri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gender Tenglik Asosiy Inson Huquqlaridan Biri",
                "verbose_name_plural": "Gender Tenglik Asosiy Inson Huquqlaridan Biri",
            },
        ),
        migrations.CreateModel(
            name="GenderTenglikkaOidMeyoriyHujjatlarniIshlabChiqish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gender Tenglikka Oid Meyoriy Hujjatlarni Ishlab Chiqish",
                "verbose_name_plural": "Gender Tenglikka Oid Meyoriy Hujjatlarni Ishlab Chiqish",
            },
        ),
        migrations.CreateModel(
            name="IshonchTelefoniReglamenti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ishonch Telefoni Reglamenti",
                "verbose_name_plural": "Ishonch Telefoni Reglamenti",
            },
        ),
        migrations.CreateModel(
            name="Korsatkichlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Korsatkichlar",
                "verbose_name_plural": "Korsatkichlar",
            },
        ),
        migrations.CreateModel(
            name="LogistikaSamaradorligiIndeksiBoyichaOchiqMalumotlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Logistika Samaradorligi Indeksi Boyicha Ochiq Malumotlar",
                "verbose_name_plural": "Logistika Samaradorligi Indeksi Boyicha Ochiq Malumotlar",
            },
        ),
        migrations.CreateModel(
            name="MeyoriyHujjatlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Meyoriy Hujjatlar",
                "verbose_name_plural": "Meyoriy Hujjatlar",
            },
        ),
        migrations.CreateModel(
            name="MeyorVazirlikdaGenderSiyosatiiyHujjatlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Meyor Vazirlikda Gender Siyosatiiy Hujjatlar",
                "verbose_name_plural": "Meyor Vazirlikda Gender Siyosatiiy Hujjatlar",
            },
        ),
        migrations.CreateModel(
            name="MurojaatlarniKoribchiqishTartibi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Murojaatlarni Koribchiqish Tartibi",
                "verbose_name_plural": "Murojaatlarni Koribchiqish Tartibi",
            },
        ),
        migrations.CreateModel(
            name="MurojaatlarStatistikasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Murojaatlar Statistikasi",
                "verbose_name_plural": "Murojaatlar Statistikasi",
            },
        ),
        migrations.CreateModel(
            name="UmumiyMalumotlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Umumiy Malumotlar",
                "verbose_name_plural": "Umumiy Malumotlar",
            },
        ),
        migrations.CreateModel(
            name="VazirlikdaGenderSiyosati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vazirlikda Gender Siyosati",
                "verbose_name_plural": "Vazirlikda Gender Siyosati",
            },
        ),
        migrations.CreateModel(
            name="YoshlarMarkaziYangiliklari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoshlar Markazi Yangiliklari",
                "verbose_name_plural": "Yoshlar Markazi Yangiliklari",
            },
        ),
        migrations.CreateModel(
            name="YoshlarSiyosati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoshlar Siyosati",
                "verbose_name_plural": "Yoshlar Siyosati",
            },
        ),
        migrations.CreateModel(
            name="YoshlarSiyosatigaOidMeyoriyHuquqiyHujjatlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoshlar Siyosatiga Oid Meyoriy Huquqiy Hujjatlar",
                "verbose_name_plural": "Yoshlar Siyosatiga Oid Meyoriy Huquqiy Hujjatlar",
            },
        ),
        migrations.CreateModel(
            name="YurtimizdaGenderTenglikniTaminlashStrategiyasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.TextField(
                        default="Default Text", verbose_name="Text (English)"
                    ),
                ),
                (
                    "text_ru",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Russian)"
                    ),
                ),
                (
                    "text_uz",
                    models.TextField(
                        default="Default Text", verbose_name="Text (Uzbek)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yurtimizda Gender Tenglikni Taminlash Strategiyasi",
                "verbose_name_plural": "Yurtimizda Gender Tenglikni Taminlash Strategiyasi",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={"verbose_name": "Boglanish", "verbose_name_plural": "Boglanish"},
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "PDF", "verbose_name_plural": "PDF"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Boshlliqlar",
                "verbose_name_plural": "Boshlliqlar",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Galereya", "verbose_name_plural": "Galereya"},
        ),
        migrations.AlterModelOptions(
            name="logo",
            options={
                "verbose_name": "Boshqa sayt linklari",
                "verbose_name_plural": "Boshqa sayt linklari",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "verbose_name": "Yangiliklar",
                "verbose_name_plural": "Yangiliklar",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Tender/Mahsulot",
                "verbose_name_plural": "Tender/Mahsulot",
            },
        ),
        migrations.AlterModelOptions(
            name="productinfo",
            options={
                "verbose_name": "Tender/Mahsulot qisqa malumot",
                "verbose_name_plural": "Tender/Mahsulot qisqa malumot",
            },
        ),
        migrations.AlterField(
            model_name="application",
            name="first_name",
            field=models.CharField(
                default="Default First Name", max_length=100, verbose_name="Ismi"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="last_name",
            field=models.CharField(
                default="Default Last Name", max_length=100, verbose_name="Sharifi"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone_number",
            field=models.CharField(
                default="Default Phone Number",
                max_length=20,
                verbose_name="Telefon raqami",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name_en",
            field=models.CharField(
                default="Default Full Name",
                max_length=100,
                verbose_name="Ismi Sharifi Familiyasi (English)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name_ru",
            field=models.CharField(
                default="Default Full Name",
                max_length=100,
                verbose_name="Ismi Sharifi Familiyasi (Russian)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name_uz",
            field=models.CharField(
                default="Default Full Name",
                max_length=100,
                verbose_name="Ismi Sharifi Familiyasi (Uzbek)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Telefon raqami"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position_en",
            field=models.CharField(
                default="Default Position",
                max_length=100,
                verbose_name="Lavozmi (English)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position_ru",
            field=models.CharField(
                default="Default Position",
                max_length=100,
                verbose_name="Lavozmi (Russian)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position_uz",
            field=models.CharField(
                default="Default Position",
                max_length=100,
                verbose_name="Lavozmi (Uzbek)",
            ),
        ),
        migrations.AlterField(
            model_name="interaktivxizmat",
            name="title_en",
            field=models.CharField(
                default="Default Name",
                max_length=100,
                verbose_name="Xizmat nomi (English)",
            ),
        ),
        migrations.AlterField(
            model_name="interaktivxizmat",
            name="title_ru",
            field=models.CharField(
                default="Default Name",
                max_length=100,
                verbose_name="Xizmat nomi (Russian)",
            ),
        ),
        migrations.AlterField(
            model_name="interaktivxizmat",
            name="title_uz",
            field=models.CharField(
                default="Default Name",
                max_length=100,
                verbose_name="Xizmat nomi (Uzbek)",
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Logotip"),
        ),
        migrations.AlterField(
            model_name="logo",
            name="text_en",
            field=models.TextField(
                default="Default Text", verbose_name="Nomi (English)"
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="text_ru",
            field=models.TextField(
                default="Default Text", verbose_name="Nomi (Russian)"
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="text_uz",
            field=models.TextField(default="Default Text", verbose_name="Nomi (Uzbek)"),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_en",
            field=models.TextField(
                default="Default Text", verbose_name="Engili haqida malumot (English)"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_ru",
            field=models.TextField(
                default="Default Text", verbose_name="Engili haqida malumot (Russian)"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_uz",
            field=models.TextField(
                default="Default Text", verbose_name="Engili haqida malumot (Uzbek)"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_en",
            field=models.CharField(
                default="Default Title",
                max_length=200,
                verbose_name="Engili nomi (English)",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_ru",
            field=models.CharField(
                default="Default Title",
                max_length=200,
                verbose_name="Engili nomi (Russian)",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_uz",
            field=models.CharField(
                default="Default Title",
                max_length=200,
                verbose_name="Engili nomi (Uzbek)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                default="Default Description",
                verbose_name="Mahsulot haqida malumot (English)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.TextField(
                default="Default Description",
                verbose_name="Mahsulot haqida malumot (Russian)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=models.TextField(
                default="Default Description",
                verbose_name="Mahsulot haqida malumot (Uzbek)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                default="Default Name",
                max_length=100,
                verbose_name="Mahsulot nomi (English)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                default="Default Name",
                max_length=100,
                verbose_name="Mahsulot nomi (Russian)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(
                default="Default Name",
                max_length=100,
                verbose_name="Mahsulot nomi (Uzbek)",
            ),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="text_en",
            field=models.TextField(verbose_name="Qo'shimcha ma'lumot (English)"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="text_ru",
            field=models.TextField(verbose_name="Qo'shimcha ma'lumot (Russian)"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="text_uz",
            field=models.TextField(verbose_name="Qo'shimcha ma'lumot (Uzbek)"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="title_en",
            field=models.CharField(max_length=100, verbose_name="sarlavha (English)"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="title_ru",
            field=models.CharField(max_length=100, verbose_name="sarlavha (Russian)"),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="title_uz",
            field=models.CharField(max_length=100, verbose_name="sarlavha (Uzbek)"),
        ),
        migrations.AlterField(
            model_name="vazirlik",
            name="text_en",
            field=models.TextField(
                default="Default Text", verbose_name="Batafsil malumot (English)"
            ),
        ),
        migrations.AlterField(
            model_name="vazirlik",
            name="text_ru",
            field=models.TextField(
                default="Default Text", verbose_name="Batafsil malumot (Russian)"
            ),
        ),
        migrations.AlterField(
            model_name="vazirlik",
            name="text_uz",
            field=models.TextField(
                default="Default Text", verbose_name="Batafsil malumot (Uzbek)"
            ),
        ),
        migrations.AlterField(
            model_name="vazirlik",
            name="title_en",
            field=models.CharField(
                default="Default Title",
                max_length=100,
                verbose_name="sarlavha (English)",
            ),
        ),
        migrations.AlterField(
            model_name="vazirlik",
            name="title_ru",
            field=models.CharField(
                default="Default Title",
                max_length=100,
                verbose_name="sarlavha (Russian)",
            ),
        ),
        migrations.AlterField(
            model_name="vazirlik",
            name="title_uz",
            field=models.CharField(
                default="Default Title", max_length=100, verbose_name="sarlavha (Uzbek)"
            ),
        ),
    ]
