# Generated by Django 5.0.4 on 2024-06-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_davlattashkilotlari_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product/Tender', 'verbose_name_plural': 'Products/Tenders'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='group_deal',
            field=models.BooleanField(default=False, verbose_name='Group Deal'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer Country'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price per Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Number'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='product',
            name='trade_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Trade Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Warranty Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(default='Default Description', verbose_name='Product Description (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default='Default Description', verbose_name='Product Description (Russian)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default='Default Description', verbose_name='Product Description (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='Product Name (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='Product Name (Russian)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default='Default Name', max_length=100, verbose_name='Product Name (Uzbek)'),
        ),
    ]
