# Generated by Django 5.0.4 on 2024-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_tenderlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderlar',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец тедера'),
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало даты'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='text_en',
            field=models.TextField(default='Default Text', verbose_name='текст (English)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='text_ru',
            field=models.TextField(default='Default Text', verbose_name='т екст (Russian)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='text_uz',
            field=models.TextField(default='Default Text', verbose_name='текст (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='title_en',
            field=models.TextField(default='Default Text', verbose_name='Загаловок (English)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='title_ru',
            field=models.TextField(default='Default Text', verbose_name='Загаловок (Russian)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='title_uz',
            field=models.TextField(default='Default Text', verbose_name='Загаловок (Uzbek)'),
        ),
    ]
