# Generated by Django 5.0.4 on 2024-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_tenderlar_end_date_tenderlar_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderlar',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
    ]
