# Generated by Django 5.0.4 on 2024-06-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_tenderlar_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenderlar',
            options={'verbose_name': 'Тендеры и конкурсы', 'verbose_name_plural': 'Тендеры и конкурсы'},
        ),
        migrations.AddField(
            model_name='tenderlar',
            name='status',
            field=models.CharField(choices=[('Закупки', 'Закупки'), ('Продажи', 'Продажи'), ('Результаты торгов', 'Результаты торгов'), ('Предприятия с негативным опытом', 'Предприятия с негативным опытом'), ('Архив', 'Архив')], default='Закупки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец тендера'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='text_en',
            field=models.TextField(default='Default Text', verbose_name='Текст (English)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='text_ru',
            field=models.TextField(default='Default Text', verbose_name='Текст (Russian)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='text_uz',
            field=models.TextField(default='Default Text', verbose_name='Текст (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='title_en',
            field=models.TextField(default='Default Text', verbose_name='Заголовок (English)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='title_ru',
            field=models.TextField(default='Default Text', verbose_name='Заголовок (Russian)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='title_uz',
            field=models.TextField(default='Default Text', verbose_name='Заголовок (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='tenderlar',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
